eZTest:
    path: /test/{contentId}
    defaults:
        _controller: eZDemoBundle:Demo:test
        contentId: 102
    requirements:
        contentId: \d+

eZTestWithLegacy:
    path: /test/legacy/{contentId}
    defaults:
        _controller: eZDemoBundle:Demo:testWithLegacy
        contentId: 102

eZTestCreateContent:
    path: /test/create/{contentId}
    defaults:
        _controller: eZDemoBundle:Demo:testCreateContent
    requirements:
        contentId: \d+
