eZTest:
    pattern: /test/{contentId}
    defaults:
        _controller: eZDemoBundle:Demo:test
        contentId: 102
    requirements:
        contentId: \d+

eZTestWithLegacy:
    pattern: /test/legacy
    defaults:
        _controller: eZDemoBundle:Demo:testWithLegacy

eZHelloWorld:
    pattern: /helloWorld
    defaults:
        _controller: eZDemoBundle:Demo:helloWorld
        name: World

eZHelloWorldTwig:
    pattern: /helloWorldTwig
    defaults:
        _controller: eZDemoBundle:Demo:helloWorldTwig

eZEditorial:
    pattern: /Editorial/{contentId}
    defaults:
        _controller: eZDemoBundle:Demo:editorial
